:experimental:

= Input Language Flag Overlay

Windows program to display the active keyboard layout using a big-ass semi-transparent flag overlay over the desktop.

== Notes

IMPORTANT: https://superuser.com/a/504089[Probably only works if the keyboard layout is configured globally.]

Only tracks keyboard layout switching via the default hotkeys: kbd:[Win+Space] (forward) and kbd:[Shift+Win+Space] (backward).

== Building

* Install https://autohotkey.com/[AutoHotkey].
Preferably the Unicode 64-bit version (tested with v1.1.29.01+).
* Add `%Program Files%\AutoHotkey\Compiler` to your `%Path%`.
Needed by a custom build step in the Visual Studio project that `Ahk2Exe` to create an executable.
* Checkout the source and open it in Visual Studio.
Build the project by selecting Debug/Release and x86/x64.

== Attribution

https://www.iconfinder.com/icons/314730/flag_icon[The icon of the executable] produced by the build was created by http://yannicklung.com/[Yannick Lung].
