:experimental:

= Input Language Overlay

Windows program to display the active keyboard layout using a big-ass semi-transparent overlay over the desktop.
Custom images can be used through creating a configuration file at `%USERPROFILE%\ilo.ini` with contents like this

```
[default]
opacity=70

[hu]
image=red.png

[en]
image=en.png
```

Section and key names in the `.ini` file are case-insensitive.

== Notes

IMPORTANT: https://superuser.com/a/504089[Probably only works if the keyboard layout is configured globally.]

Only tracks keyboard layout switching via the default hotkeys: kbd:[Win+Space] (forward) and kbd:[Shift+Win+Space] (backward).

== Building

* Install https://autohotkey.com/[AutoHotkey].
Preferably the Unicode 64-bit version (tested with v1.1.29.01+).
* Add `%PROGRAMFILES%\AutoHotkey\Compiler` to your `%PATH%`.
Needed by a custom build step in the Visual Studio project that `Ahk2Exe` to create an executable.
* Checkout the source and open it in Visual Studio.
Build the project by selecting Debug/Release and x86/x64.

== Attribution

https://www.iconfinder.com/icons/314730/flag_icon[The icon of the executable] produced by the build was created by http://yannicklung.com/[Yannick Lung].
